name: Clone Public Repo

on:
  repository_dispatch:
    types: [cloning_cocoa_spec_repo]

jobs:
  cloning_the_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty repository
        run: |
          # Replace <YOUR_USERNAME> with your GitHub username
          # Replace <REPO_NAME> with the desired repository name
          echo "Finally echoing from github actions"
